#!/bin/sh
#/**************************************************************************
# *
# *         Copyright (c) 2011 by iCatch Technology Inc.
# *
# *  This software is copyrighted by and is the property of iCatch
# *  Technology Inc. All rights are reserved by iCatch Technology Inc.
# *  This software may only be used in accordance with the corresponding
# *  license agreement. Any unauthorized use, duplication, distribution,
# *  or disclosure of this software is expressly forbidden.
# *
# *  This Copyright notice MUST not be removed or modified without prior
# *  written consent of iCatch Technology Inc.
# *
# *  iCatch Technology Inc. reserves the right to modify this software
# *  without notice.
# *
# *  iCatch Technology Inc.
# *  19-1, Innovation First Road, Science-Based Industrial Park,
# *  Hsin-Chu, Taiwan.
# *
# **************************************************************************/
# \file   map_archive_mem_list.sh
# \brief  to list linked obj members in specific archive
# \author Anmin Deng

# \param
# ${1} is the because file name, eg, "spca7002.because", which was previously
#      generated by "$tool/multiboot_map spca7002.map spca7002.because";
# ${2} is the specific archive name, eg, "libmy.a".
# \return
# exit code 0: success; non-zero: failed
# all the linked obj members, each member separated by '\n', listed to stdout

## checking arguments

if [ $# != 2 ] ; then
	echo "${0}: usage: \`because' \`archive'" 1>&2
	exit 1
fi

bcz=${1}
lib=${2%.a}

if [ ! -f "${bcz}" ] || [ ! -r "${bcz}" ] ; then
	echo "${0}: \`${bcz}': .because file can not open" 1>&2
	exit 1
fi

sed=/bin/sed

# possible member list patterns in .because file
# ^../../lib[.fpga]/_multiboot.bak/${lib%.a}/*.o$
# ^../../lib[.fpga]/${lib}/(*.o)$

$sed -n -e "s/^.\+\/_multiboot.bak\/${lib}\/\(.\+\.o\)$/\1/p" \
	-e "s/^.\+\/${lib}\.a(\(.\+\.o\))$/\1/p" ${bcz}
