/**************************************************************************
 *
 *        Copyright (c) 2006-2008 by Sunplus mMedia Inc., Ltd.
 *
 *  This software is copyrighted by and is the property of Sunplus
 *  mMedia Inc., Ltd. All rights are reserved by Sunplus mMedia
 *  Inc., Ltd. This software may only be used in accordance with the
 *  corresponding license agreement. Any unauthorized use, duplication,
 *  distribution, or disclosure of this software is expressly forbidden.
 *
 *  This Copyright notice MUST not be removed or modified without prior
 *  written consent of Sunplus mMedia Inc., Ltd.
 *
 *  Sunplus mMedia Inc., Ltd. reserves the right to modify this
 *  software without notice.
 *
 *  Sunplus mMedia Inc., Ltd.
 *  19-1, Innovation First Road, Science-Based Industrial Park,
 *  Hsin-Chu, Taiwan, R.O.C. 
 *
 **************************************************************************/


#ifndef _APP_OSDFONT_H_
#define _APP_OSDFONT_H_

/*********FONT SIZE************************************************/
#define FontEngNumSize_X	16
#define FontEngNumSize_Y	28



#define ID_MENU_TKMENUBODY					"A:\\RO_RES\\UI\\ICON\\MUBODY.SFN"
#define ID_MENU_TKMENUSELBAR					"A:\\RO_RES\\UI\\ICON\\MUBAR.SFN"
#define ID_MENU_TYMENUMAINVIEWCLEARBAR		"A:\\RO_RES\\UI\\ICON\\MUBARCL.SFN"
#define ID_MENU_TKMENU_MENUBODYHL			"A:\\RO_RES\\UI\\ICON\\MUBODYHL.SFN"
#define ID_MENU_TKMENU_MENUSUBUBAR			"A:\\RO_RES\\UI\\ICON\\MUBARHD.SFN"
#define ID_MENU_TKMENU_SUBMENU_4ITEMSC		"A:\\RO_RES\\UI\\ICON\\MUSUBSC.SFN"
#define ID_MENU_TKMENU_SUBMENUBAR			"A:\\RO_RES\\UI\\ICON\\MUSBAR.SFN"
#define ID_MENU_TKMENU_SUBMENU_3ITEM		"A:\\RO_RES\\UI\\ICON\\MUSUB3.SFN"
#define ID_MENU_TKMENU_SUBMENU_2ITEM		"A:\\RO_RES\\UI\\ICON\\MUSUB2.SFN"
#define ID_MENU_TKMENU_SUBMENU_CLEARBAR		"A:\\RO_RES\\UI\\ICON\\MUSBARCL.SFN"
#define ID_MENU_TKMENU_SUBMENU_4ITEM		"A:\\RO_RES\\UI\\ICON\\MUSUB4.SFN"

#define ID_WARNFRAME							"A:\\RO_RES\\UI\\ICON\\WARN.SFN"
#define ID_WARNICON							"A:\\RO_RES\\UI\\ICON\\WARNICON.SFN"
#define ID_WARNFRAME2						"A:\\RO_RES\\UI\\ICON\\WARNBG2.SFN"

/*
#define ID_FONT_TK_FONT1						"UI\\ICON\\ICON56.SFN"
#define ID_FONT_TK_ICON						"UI\\ICON\\ICONTK.SFN"
*/
#define ID_FONT_ICON	appOsd_FontIconResSelect()

#define ID_ICON_LCM_TEST					"UI\\ICON\\LCM_TEST.SFN"

#define ID_ICON_ZOOM						"UI\\ICON\\ZOOM.SFN"
#define ID_ICON_WARNMEDIASTANDBY			"UI\\ICON\\WARNM.SFN"
#define ID_ICON_FOCUS						"UI\\ICON\\FOCUS.SFN"
#define ID_FONT_TK_TIME							"UI\\ICON\\TIMEBQ.SFN"
#define ID_FONT_TK_TIME_HDMI					"UI\\ICON\\TIMEBQ_HDMI.SFN"


#define ID_JPG_RES_USB_MODE					"A:\\RO_RES\\UI\\JPG\\SCRBLACK.JPG"


#define ID_JPG_RES_USB_MODE					"A:\\RO_RES\\UI\\JPG\\SCRBLACK.JPG"



#define ID_ICON_TK_SETUPBODY				"A:\\RO_RES\\UI\\ICON\\SEBODY.SFN"
#define ID_ICON_TK_SUMENUUBAR				"A:\\RO_RES\\UI\\ICON\\SUMUBAR.SFN"
#define ID_ICON_TK_CLEAR_SUMENUUBAR			"A:\\RO_RES\\UI\\ICON\\SUMUBARC.SFN"
#define ID_ICON_TK_MENUBODYHL				"A:\\RO_RES\\UI\\ICON\\MUBODYHL.SFN"
#define ID_ICON_TK_HIDDEN_MENUSUBUBAR		"A:\\RO_RES\\UI\\ICON\\MUBARHD.SFN"
#define ID_ICON_TK_MENUSISUBUBAR			"A:\\RO_RES\\UI\\ICON\\MUSIBAR.SFN"
#define ID_ICON_TK_SUMENUSUBUBAR			"A:\\RO_RES\\UI\\ICON\\SUMUSBAR.SFN"
#define ID_ICON_TK_SUMENUSUB2				"A:\\RO_RES\\UI\\ICON\\SUMUSUB2.SFN"
#define ID_ICON_TK_SUMENUSUB3				"A:\\RO_RES\\UI\\ICON\\SUMUSUB3.SFN"
#define ID_ICON_TK_SUMENUSUB4				"A:\\RO_RES\\UI\\ICON\\SUMUSUB4.SFN"
#define ID_ICON_TK_SUMENUSUB4SCROLL			"A:\\RO_RES\\UI\\ICON\\SUMUSUBS.SFN"
#define ID_ICON_TK_CLEAR_SUMENUSUBUBAR		"A:\\RO_RES\\UI\\ICON\\SUMUSBCL.SFN"
#define ID_ICON_TK_CLEAR_SUMENUSISUBUBAR		"A:\\RO_RES\\UI\\ICON\\MSIBARCL.SFN"
#define ID_ICON_TK_VOLUME_BAR				"A:\\RO_RES\\UI\\ICON\\VOLBAR.SFN"
#define ID_ICON_TK_VOLUME_BAR_HL			"A:\\RO_RES\\UI\\ICON\\VOLBARHL.SFN"
#define ID_ICON_TK_SMU2BAR 					"A:\\RO_RES\\UI\\ICON\\SMU2BAR.SFN"   
/*#define ID_MENU_TK_2NDMENU2					"A:\\RO_RES\\UI\\ICON\\MU2ND2.SFN"
#define ID_MENU_TK_2NDMENU3					"A:\\RO_RES\\UI\\ICON\\MU2ND3.SFN"*/

#define ID_MENU_TK_MENUSUBSETBAR			"A:\\RO_RES\\UI\\ICON\\MUSUSBAR.SFN"
#define ID_MENU_TK_SLSHOWBAR				"A:\\RO_RES\\UI\\ICON\\MUSLBAR.SFN"
#define ID_MENU_TK_MENUDT					"A:\\RO_RES\\UI\\ICON\\MUDT.SFN"

/*#define ID_DLGBOX_TXT_TITLE_ICON			"A:\\RO_RES\\UI\\ICON\\DLGTITLL.SFN"*/
#define ID_DLGBOX_TXT2_TITLE_ICON			"A:\\RO_RES\\UI\\ICON\\MU2ND2.SFN"
#define ID_DLGBOX_TXT2_TITLE_ICON_HDMI	"A:\\RO_RES\\UI\\ICON\\MU2ND2_HDMI.SFN"
#define ID_DLGBOX_TXT3_TITLE_ICON			"A:\\RO_RES\\UI\\ICON\\MU2ND3.SFN"
#define ID_DLGBOX_TXT3_TITLE_ICON_HDMI	"A:\\RO_RES\\UI\\ICON\\MU2ND3_HDMI.SFN"
#define ID_DLGBOX_TXT4_TITLE_ICON			"A:\\RO_RES\\UI\\ICON\\MUSUBSC.SFN"
#define ID_DLGBOX_TXT4_TITLE_ICON_HDMI	"A:\\RO_RES\\UI\\ICON\\MUSUBSC_HDMI.SFN"

#define ID_DLGBOX_NULL_TITLE_ICON			"A:\\RO_RES\\UI\\ICON\\DLGOPTTP.SFN"
#define ID_DLGBOX_OPTION_TXT_ICON			"A:\\RO_RES\\UI\\ICON\\DLGOPTCT.SFN"
#define ID_DLGBOX_OPTION_BOTTOM_ICON		"A:\\RO_RES\\UI\\ICON\\DLGOPTBT.SFN"
#define ID_MENU_TK_MENUSCENE				"A:\\RO_RES\\UI\\ICON\\MUSCENE.SFN"


/*s willow modify for reduce size@20100602*/
#define ID_MENU_TK_SUBMENUSCROLL_TYPE      "A:\\RO_RES\\UI\\ICON\\SSCR.SFN"  
/*e willow modify for reduce size@20100602*/

#define ID_STR_TBL_ENG				"UI\\SST\\ENGLISH.SST"
#define ID_STRTK_TBL_ENG			"UI\\SST\\ENGLISH.SST" /*"UI\\SST\\STR5KTK.SST"*/
#define ID_STRTK_TBL_TCH			"UI\\SST\\TCHINESE.SST" /*"UI\\SST\\TTCHSTR.SST"*/
#define ID_STRTK_TBL_SCH			"UI\\SST\\SCHINESE.SST" /*"UI\\SST\\TSCHSTR.SST"*/
#define ID_STRTK_TBL_GERMAN			"UI\\SST\\TGERSTR.SST"
#define ID_STRTK_TBL_CZECH			"UI\\SST\\TCZESTR.SST"
#define ID_STRTK_TBL_DUTCH			"UI\\SST\\TDUTSTR.SST"
#define ID_STRTK_TBL_FRENCH			"UI\\SST\\TFRESTR.SST"
#define ID_STRTK_TBL_GREEK			"UI\\SST\\TGREESTR.SST"
#define ID_STRTK_TBL_HUNGARIAN		"UI\\SST\\THUNSTR.SST"
#define ID_STRTK_TBL_ITALIAN		"UI\\SST\\TITALSTR.SST"
#define ID_STRTK_TBL_INDONESIAN		"UI\\SST\\TINDSTR.SST"
#define ID_STRTK_TBL_MALAY			"UI\\SST\\TMALYSTR.SST"
#define ID_STRTK_TBL_POLISH			"UI\\SST\\TPOLSTR.SST"
#define ID_STRTK_TBL_PORTUGUESE		"UI\\SST\\TPORTSTR.SST"
#define ID_STRTK_TBL_RUSSIAN		"UI\\SST\\TRUSSTR.SST"
#define ID_STRTK_TBL_ROMANIAN		"UI\\SST\\TROMSTR.SST"
#define ID_STRTK_TBL_SPANISH		"UI\\SST\\TSPANSTR.SST"
#define ID_STRTK_TBL_SWEDISH		"UI\\SST\\TSWEDSTR.SST"
#define ID_STRTK_TBL_TURKISH		"UI\\SST\\TTURKSTR.SST"
#define ID_STRTK_TBL_CROATION		"UI\\SST\\TCROASTR.SST"
#define ID_STRTK_TBL_ARABIC			"UI\\SST\\TARASTR.SST"
#define ID_STRTK_TBL_THAI			"UI\\SST\\TTHAISTR.SST"
#define ID_STRTK_TBL_JAPAN			"UI\\SST\\TJAPSTR.SST"	
#define ID_STRTK_TBL_KOREAN			"UI\\SST\\TKORSTR.SST"

#define ID_FONT_ENG     			"UI\\FONT\\ENGLISH_32.SFN"
#define ID_FONT_ENG22X28			"UI\\FONT\\ENGLISH_32.SFN" /*"UI\\FONT\\FONTENG.SFN"*/
#define ID_FONT_TCH28X28			"UI\\FONT\\TCHINESE_32.SFN" /*"UI\\FONT\\TCHFONT.SFN"*/
#define ID_FONT_SCH28X28			"UI\\FONT\\SCHINESE_32.SFN" /*"UI\\FONT\\SCHFONT.SFN"*/
#define ID_FONT_ARABIC28X28			"UI\\FONT\\ARAFONT_32.SFN"
#define ID_FONT_THAI28X28			"UI\\FONT\\FONTTAI_32.SFN"
#define ID_FONT_JAPAN28x28			"UI\\FONT\\JAPFONT_32.SFN"
#define ID_FONT_KOREAN28X28			"UI\\FONT\\KORFONT_32.SFN"
#define ID_FONT_ITALIAN28x28			"UI\\FONT\\ITALIAN_32.SFN"
#define ID_FONT_GERMAN28x28			"UI\\FONT\\GERMAN_32.SFN"
#define ID_FONT_SPANISH28x28			"UI\\FONT\\SPANISH_32.SFN"
#define ID_FONT_PORTUGUESE28x28			"UI\\FONT\\PORTUGUESE_32.SFN"
#define ID_FONT_VIETNAMESE28x28			"UI\\FONT\\VIETNAMESE_32.SFN"
#define ID_FONT_FRENCH28x28			"UI\\FONT\\FRENCH_32.SFN"
#define ID_FONT_DUTCH28x28			"UI\\FONT\\DUTCH_32.SFN"
#define ID_FONT_GREEK28x28			"UI\\FONT\\GREEK_32.SFN"
#define ID_FONT_KOREAN28x28			"UI\\FONT\\KOREAN_32.SFN"
#define ID_FONT_CZECH28x28			"UI\\FONT\\CZECH_32.SFN"
#define ID_FONT_HUNGARIAN28x28			"UI\\FONT\\HUNGARIAN_32.SFN"
#define ID_FONT_POLISH28x28			"UI\\FONT\\POLISH_32.SFN"
#define ID_FONT_TURKISH28x28			"UI\\FONT\\TURKISH_32.SFN"
#define ID_FONT_RUSSIAN28x28			"UI\\FONT\\RUSSIAN_32.SFN"
#define ID_FONT_SWEDISH28x28			"UI\\FONT\\SWEDISH_32.SFN"
#define ID_FONT_ROMANIAN28x28			"UI\\FONT\\ROMANIAN_32.SFN"
#define ID_FONT_CROATION28x28			"UI\\FONT\\CROATION_32.SFN"
#define ID_FONT_MALAY28x28			"UI\\FONT\\MALAY_32.SFN"
#define ID_FONT_ARABIC28x28			"UI\\FONT\\ARABIC_32.SFN"
#define ID_FONT_HINDI28x28			"UI\\FONT\\HINDI_32.SFN"
#define ID_FONT_MARATHI28x28			"UI\\FONT\\MARATHI_32.SFN"
#define ID_FONT_URDU28x28			"UI\\FONT\\URDU_32.SFN"
#define ID_FONT_BENGALI28x28			"UI\\FONT\\BENGALI_32.SFN"
#define ID_FONT_PUNJABI28x28			"UI\\FONT\\PUNJABI_32.SFN"
#define ID_FONT_TELEGU28x28			"UI\\FONT\\TELEGU_32.SFN"
#define ID_FONT_ORIYA28x28			"UI\\FONT\\ORIYA_32.SFN"


#define ID_FONT_ENG_HDMI			"UI\\FONT\\ENGLISH_42.SFN"
#define ID_FONT_TCH_HDMI			"UI\\FONT\\TCHINESE_42.SFN"
#define ID_FONT_SCH_HDMI			"UI\\FONT\\SCHINESE_42.SFN"
#define ID_FONT_ARABIC_HDMI			"UI\\FONT\\ARAFONT_42.SFN"
#define ID_FONT_THAI_HDMI			"UI\\FONT\\FONTTAI_42.SFN"
#define ID_FONT_JAPAN_HDMI			"UI\\FONT\\JAPFONT_42.SFN"
#define ID_FONT_KOREAN_HDMI			"UI\\FONT\\KORFONT_42.SFN"
#define ID_FONT_ITALIAN_HDMI			"UI\\FONT\\ITALIAN_42.SFN"
#define ID_FONT_GERMAN_HDMI		    "UI\\FONT\\GERMAN_42.SFN"
#define ID_FONT_SPANISH_HDMI			"UI\\FONT\\SPANISH_42.SFN"
#define ID_FONT_PORTUGUESE_HDMI			"UI\\FONT\\PORTUGUESE_42.SFN"
#define ID_FONT_VIETNAMESE_HDMI		"UI\\FONT\\VIETNAMESE_42.SFN"
#define ID_FONT_FRENCH_HDMI			"UI\\FONT\\FRENCH_42.SFN"
#define ID_FONT_DUTCH_HDMI			"UI\\FONT\\DUTCH_42.SFN"
#define ID_FONT_GREEK_HDMI			"UI\\FONT\\GREEK_42.SFN"
#define ID_FONT_CZECH_HDMI			"UI\\FONT\\CZECH_42.SFN"
#define ID_FONT_HUNGARIAN_HDMI			"UI\\FONT\\HUNGARIAN_42.SFN"
#define ID_FONT_POLISH_HDMI			"UI\\FONT\\POLISH_42.SFN"
#define ID_FONT_TURKISH_HDMI			"UI\\FONT\\TURKISH_42.SFN"
#define ID_FONT_RUSSIAN_HDMI			"UI\\FONT\\RUSSIAN_42.SFN"
#define ID_FONT_SWEDISH_HDMI			"UI\\FONT\\SWEDISH_42.SFN"
#define ID_FONT_ROMANIAN_HDMI			"UI\\FONT\\ROMANIAN_42.SFN"
#define ID_FONT_CROATION_HDMI			"UI\\FONT\\CROATION_42.SFN"
#define ID_FONT_MALAY_HDMI			"UI\\FONT\\MALAY_42.SFN"
#define ID_FONT_HINDI_HDMI			"UI\\FONT\\HINDI_42.SFN"
#define ID_FONT_MARATHI_HDMI			"UI\\FONT\\MARATHI_42.SFN"
#define ID_FONT_URDU_HDMI			"UI\\FONT\\URDU_42.SFN"
#define ID_FONT_BENGALI_HDMI			"UI\\FONT\\BENGALI_42.SFN"
#define ID_FONT_PUNJABI_HDMI			"UI\\FONT\\PUNJABI_42.SFN"
#define ID_FONT_TELEGU_HDMI		"UI\\FONT\\TELEGU_42.SFN"
#define ID_FONT_ORIYA_HDMI			"UI\\FONT\\ORIYA_42.SFN"

#endif /* _APP_OSDFONT_H_ */





