/****************************************************************************
 *                                                                          *
 *         Copyright (c) 2012 by Sunplus-prof Technology Co., Ltd.          *
 *                                                                          *
 *  This software is copyrighted by and is the property of Sunplus-prof     *
 *  Technology Co., Ltd. All rights are reserved by Sunplus-prof Technology *
 *  Co., Ltd. This software may only be used in accordance with the         *
 *  corresponding license agreement. Any unauthorized use, duplication,     *
 *  distribution, or disclosure of this software is expressly forbidden.    *
 *                                                                          *
 *  This Copyright notice MUST not be removed or modified without prior     *
 *  written consent of Sunplus-prof Technology Co., Ltd.                    *
 *                                                                          *
 *  Sunplus-prof Technology Co., Ltd. reserves the right to modify this     *
 *  software without notice.                                                *
 *                                                                          *
 *  Sunplus-prof Technology Co., Ltd.                                       *
 *  2nd Floor,R2-B,Hi-tech.S,7th Road, Shenzhen High-tech Industrial Park   *
 *  Shenzhen, China                                                         *
 *                                                                          *
 *  Author: Joe Zhao                                                        *
 *                                                                          *
 ****************************************************************************/
/* Sunplus-prof   Joe Zhao   July,07,2015  10:34:07 For SPCA6330A */
/* This file is created by tool, don't modify it!!! */

#ifndef _MENU_RES_H_
#define _MENU_RES_H_

[LANGUAGE]english:

[MARK]MENU_MARK_SPORT_DV:
"CAM MENU",		"scdv_sport_dv.bmp",		[()appMenuEvt_ModeSportDV],
	"VIDEO MODE...",		"sdv_video_mode.bmp",		[appMenuAct_SdvVideoMode(SdvVideoMode)appMenuEvt_SdvVideoModeInit],
		"VIDEO MODE",		"sdv_video_mode_normal.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoModeSet],
			"RESOLUTION",		"sdv_video_size_1080p30.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoNormalSizeSet],
			"RESOLUTION",		"sdv_video_size_960p30.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoNormalSizeSet],
			"RESOLUTION",		"sdv_video_size_720p60.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoNormalSizeSet],
			"RESOLUTION",		"sdv_video_size_720p30.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoNormalSizeSet],
			"RESOLUTION",		"sdv_video_size_wvgap60.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoNormalSizeSet],
			"RESOLUTION",		"sdv_video_size_wvgap30.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoNormalSizeSet],
			"RESOLUTION",		"sdv_video_size_vgap90.bmp",		[(SdvVideoNormalSize)appMenuEvt_SdvVideoNormalSizeSet],
		"VIDEO MODE",		"sdv_video_mode_slow.bmp",		[(SdvVideoSlowTime)appMenuEvt_SdvVideoModeSet],
			"SLOW VIDEO",		"sdv_video_slow_time_1_2.bmp",		[(SdvVideoSlowTime)appMenuEvt_SdvVideoSlowTimeSet],
			"SLOW VIDEO",		"sdv_video_slow_time_1_3.bmp",		[(SdvVideoSlowTime)appMenuEvt_SdvVideoSlowTimeSet],
			"SLOW VIDEO",		"sdv_video_slow_time_1_4.bmp",		[(SdvVideoSlowTime)appMenuEvt_SdvVideoSlowTimeSet],
	"PHOTO MODE...",		"sdv_photo_mode.bmp",		[appMenuAct_SdvPhotoMode(SdvPhotoMode)appMenuEvt_SdvPhotoModeInit],
		"NORMAL",		"sdv_photo_mode_normal.bmp",		[(SdvPhotoNormalSize)appMenuEvt_SdvPhotoModeSet],
			"SIZE",		"sdv_photo_size_05m.bmp",		[(SdvPhotoNormalSize)appMenuEvt_SdvPhotoNormalSizeSet],
			"SIZE",		"sdv_photo_size_03m.bmp",		[(SdvPhotoNormalSize)appMenuEvt_SdvPhotoNormalSizeSet],
			"SIZE",		"sdv_photo_size_02m.bmp",		[(SdvPhotoNormalSize)appMenuEvt_SdvPhotoNormalSizeSet],
		"BURST",		"sdv_photo_mode_burst.bmp",		[(SdvPhotoBurstNumber)appMenuEvt_SdvPhotoModeSet],
			"BURST COUNT",		"sdv_photo_burst_number_03.bmp",		[(SdvPhotoBurstNumber)appMenuEvt_SdvPhotoBurstTimeSet],
			"BURST COUNT",		"sdv_photo_burst_number_05.bmp",		[(SdvPhotoBurstNumber)appMenuEvt_SdvPhotoBurstTimeSet],
			"BURST COUNT",		"sdv_photo_burst_number_10.bmp",		[(SdvPhotoBurstNumber)appMenuEvt_SdvPhotoBurstTimeSet],
		"SELFTIMER",		"sdv_photo_mode_selftimer.bmp",		[(SdvPhotoSelfTimer)appMenuEvt_SdvPhotoModeSet],
			"TIMER DELAY",		"sdv_photo_self_timer_02S.bmp",		[(SdvPhotoSelfTimer)appMenuEvt_SdvPhotoSelfTimerSet],
			"TIMER DELAY",		"sdv_photo_self_timer_05S.bmp",		[(SdvPhotoSelfTimer)appMenuEvt_SdvPhotoSelfTimerSet],
			"TIMER DELAY",		"sdv_photo_self_timer_10S.bmp",		[(SdvPhotoSelfTimer)appMenuEvt_SdvPhotoSelfTimerSet],
	"SENSOR FLIP",		"scdv_sensor_flip.bmp",		[appMenuAct_ScdvSensorFlip(SCdvSensorFlip)],
		"SENSOR FLIP",		"scdv_auto.bmp",		[(SCdvSensorFlip)appMenuEvt_ScdvSensorFlipSet],
		"SENSOR FLIP",		"scdv_on.bmp",		[(SCdvSensorFlip)appMenuEvt_ScdvSensorFlipSet],
		"SENSOR FLIP",		"scdv_off.bmp",		[(SCdvSensorFlip)appMenuEvt_ScdvSensorFlipSet],
	"CAR DV",		"scdv_car_dv.bmp",		[appMenuAct_SdvCarDv()],
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_SdvCarDvSet],
		"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_SdvCarDvSet],
	"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_SdvExitSet],
[MARK]MENU_MARK_CAR_DV:
"CAM MENU",		"scdv_car_dv.bmp",		[()appMenuEvt_ModeCarDV],
	"VIDEO MODE...",		"cdv_video_mode.bmp",		[appMenuAct_CdvVideoMode(CdvVideoMode)appMenuEvt_CdvVideoModeInit],
		"VIDEO MODE",		"cdv_video_mode_normal.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoModeSet],
			"RESOLUTION",		"cdv_video_size_1080p30.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoNormalSet],
			"RESOLUTION",		"cdv_video_size_960p30.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoNormalSet],
			"RESOLUTION",		"cdv_video_size_720p60.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoNormalSet],
			"RESOLUTION",		"cdv_video_size_720p30.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoNormalSet],
			"RESOLUTION",		"cdv_video_size_wvgap60.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoNormalSet],
			"RESOLUTION",		"cdv_video_size_wvgap30.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoNormalSet],
			"RESOLUTION",		"cdv_video_size_vgap90.bmp",		[(CdvVideoNormalSize)appMenuEvt_CdvVideoNormalSet],
		"VIDEO MODE",		"cdv_video_mode_lapse.bmp",		[(CdvVideoLapseTime)appMenuEvt_CdvVideoModeSet],
			"VIDEO LAPSE",		"cdv_video_lapse_01s.bmp",		[(CdvVideoLapseTime)appMenuEvt_CdvVideoLapseSet],
			"VIDEO LAPSE",		"cdv_video_lapse_03s.bmp",		[(CdvVideoLapseTime)appMenuEvt_CdvVideoLapseSet],
			"VIDEO LAPSE",		"cdv_video_lapse_05s.bmp",		[(CdvVideoLapseTime)appMenuEvt_CdvVideoLapseSet],
			"VIDEO LAPSE",		"cdv_video_lapse_10s.bmp",		[(CdvVideoLapseTime)appMenuEvt_CdvVideoLapseSet],
			"VIDEO LAPSE",		"cdv_video_lapse_30s.bmp",		[(CdvVideoLapseTime)appMenuEvt_CdvVideoLapseSet],
			"VIDEO LAPSE",		"cdv_video_lapse_60s.bmp",		[(CdvVideoLapseTime)appMenuEvt_CdvVideoLapseSet],
	"LOOPING",		"cdv_looping_time.bmp",		[appMenuAct_CdvLooping(CdvLoopingTime)],
		"2MIN",		"cdv_looping_time_02min.bmp",		[(CdvLoopingTime)appMenuEvt_CdvLoopingTimeSet],
		"5MIN",		"cdv_looping_time_05min.bmp",		[(CdvLoopingTime)appMenuEvt_CdvLoopingTimeSet],
		"15MIN",		"cdv_looping_time_15min.bmp",		[(CdvLoopingTime)appMenuEvt_CdvLoopingTimeSet],
	"SENSOR FLIP",		"scdv_sensor_flip.bmp",		[appMenuAct_ScdvSensorFlip(SCdvSensorFlip)],
		"SENSOR FLIP",		"scdv_auto.bmp",		[(SCdvSensorFlip)appMenuEvt_ScdvSensorFlipSet],
		"SENSOR FLIP",		"scdv_on.bmp",		[(SCdvSensorFlip)appMenuEvt_ScdvSensorFlipSet],
		"SENSOR FLIP",		"scdv_off.bmp",		[(SCdvSensorFlip)appMenuEvt_ScdvSensorFlipSet],
	"G TRIGGER",		"cdv_gsensor_trigger.bmp",		[appMenuAct_CdvGsensorTrigger(CdvGsensorTrigger)],
		"ON",		"scdv_on.bmp",		[(CdvGsensorTrigger)appMenuEvt_CdvGsensorTriggerSet],
		"OFF",		"scdv_off.bmp",		[(CdvGsensorTrigger)appMenuEvt_CdvGsensorTriggerSet],
	"G SENSITIVITY",		"cdv_gsensor_sensitivity.bmp",		[appMenuAct_CdvGsensorSensitivity(CdvGsensorSensitivity)],
		"HIGHT",		"cdv_gsensor_sensitivity_hight.bmp",		[(CdvGsensorSensitivity)appMenuEvt_CdvGsensorSensitivitySet],
		"MIDDLE",		"cdv_gsensor_sensitivity_middle.bmp",		[(CdvGsensorSensitivity)appMenuEvt_CdvGsensorSensitivitySet],
		"LOW",		"cdv_gsensor_sensitivity_low.bmp",		[(CdvGsensorSensitivity)appMenuEvt_CdvGsensorSensitivitySet],
	"MIC PHONE",		"cdv_mic_phone.bmp",		[appMenuAct_CdvMicPhone(CdvMicPhone)],
		"ON",		"scdv_on.bmp",		[(CdvMicPhone)appMenuEvt_CdvMicPhoneSet],
		"OFF",		"scdv_off.bmp",		[(CdvMicPhone)appMenuEvt_CdvMicPhoneSet],
	"SPORT DV",		"scdv_sport_dv.bmp",		[appMenuAct_CdvSdvMode()],
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_CdvSportDvSet],
		"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_CdvSportDvSet],
	"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_CdvExitSet],
[MARK]MENU_MARK_SYSTEM1:
"SYS MENU1",		"system_1.bmp",		[()appMenuEvt_ModeSystem1],
	"DIS",		"system_dis.bmp",		[appMenuAct_SystemDis(SystemDis)],
		"ON",		"scdv_on.bmp",		[(SystemDis)appMenuEvt_SystemDisSet],
		"OFF",		"scdv_off.bmp",		[(SystemDis)appMenuEvt_SystemDisSet],
	"WDR",		"system_wdr.bmp",		[appMenuAct_SystemWdr(SystemWdr)],
		"ON",		"scdv_on.bmp",		[(SystemWdr)appMenuEvt_SystemWdrSet],
		"OFF",		"scdv_off.bmp",		[(SystemWdr)appMenuEvt_SystemWdrSet],
	"LED INDICATOR",		"system_led_indicator.bmp",		[appMenuAct_SystemLedIndicator(SystemLedIndicator)],
		"ON",		"scdv_on.bmp",		[(SystemLedIndicator)appMenuEvt_SystemLedIndicatorSet],
		"OFF",		"scdv_off.bmp",		[(SystemLedIndicator)appMenuEvt_SystemLedIndicatorSet],
	"OSD FLIP",		"system_osd_flip.bmp",		[appMenuAct_SystemOsdFlip(SystemOsdFlip)],
		"ON",		"system_osd_flip_on.bmp",		[(SystemOsdFlip)appMenuEvt_SystemOsdFlipSet],
		"OFF",		"system_osd_flip_off.bmp",		[(SystemOsdFlip)appMenuEvt_SystemOsdFlipSet],
	"OSD BRIGHTNESS",		"system_osd_brightness.bmp",		[appMenuAct_SystemOsdBrightness(SystemOsdBrightness)],
		"100%",		"system_osd_brightness_100.bmp",		[(SystemOsdBrightness)appMenuEvt_SystemOsdBrightnessSet],
		"60%",		"system_osd_brightness_60.bmp",		[(SystemOsdBrightness)appMenuEvt_SystemOsdBrightnessSet],
		"30%",		"system_osd_brightness_30.bmp",		[(SystemOsdBrightness)appMenuEvt_SystemOsdBrightnessSet],
	"BEEP VOLUME",		"system_beep_volume.bmp",		[appMenuAct_SystemBeepVolume(SystemBeepVolume)],
		"100%",		"system_beep_volume_100.bmp",		[(SystemBeepVolume)appMenuEvt_SystemBeepVolumeSet],
		"60%",		"system_beep_volume_60.bmp",		[(SystemBeepVolume)appMenuEvt_SystemBeepVolumeSet],
		"OFF",		"system_beep_volume_off.bmp",		[(SystemBeepVolume)appMenuEvt_SystemBeepVolumeSet],
	"DATE STAMP",		"system_date_stamp.bmp",		[appMenuAct_SystemDateStamp(SystemDateStamp)],
		"ON",		"scdv_on.bmp",		[(SystemDateStamp)appMenuEvt_SystemDateStampSet],
		"OFF",		"scdv_off.bmp",		[(SystemDateStamp)appMenuEvt_SystemDateStampSet],
	"AUTO POWER OFF",		"system_auto_power_off.bmp",		[appMenuAct_SystemAutoPowerOff(SystemAutoPowerOff)],
		"60MIN",		"system_auto_power_off_60min.bmp",		[(SystemAutoPowerOff)appMenuEvt_SystemAutoPowerOffSet],
		"30MIN",		"system_auto_power_off_30min.bmp",		[(SystemAutoPowerOff)appMenuEvt_SystemAutoPowerOffSet],
		"10MIN",		"system_auto_power_off_10min.bmp",		[(SystemAutoPowerOff)appMenuEvt_SystemAutoPowerOffSet],
		"5MIN",		"system_auto_power_off_05min.bmp",		[(SystemAutoPowerOff)appMenuEvt_SystemAutoPowerOffSet],
		"3MIN",		"system_auto_power_off_03min.bmp",		[(SystemAutoPowerOff)appMenuEvt_SystemAutoPowerOffSet],
		"1MIN",		"system_auto_power_off_01min.bmp",		[(SystemAutoPowerOff)appMenuEvt_SystemAutoPowerOffSet],
		"OFF",		"scdv_off.bmp",		[(SystemAutoPowerOff)appMenuEvt_SystemAutoPowerOffSet],
	"EXIT",		"scdv_exit.bmp",		[appMenuAct_System1Exit()appMenuEvt_System1ExitSet],
[MARK]MENU_MARK_SYSTEM2:
"SYS MENU2",		"system_2.bmp",		[()appMenuEvt_ModeSystem2],
	"DATE & TIME...",		"system_date_time.bmp",		[appMenuAct_SystemDateTime()appMenuEvt_SystemDateTimeInit],
		"DAY",		[(SystemDateTimeDay)appMenuEvt_SystemDateTimeSet],
			"01",		[(SystemDateTimeDay)],
			"02",		[(SystemDateTimeDay)],
			"03",		[(SystemDateTimeDay)],
			"04",		[(SystemDateTimeDay)],
			"05",		[(SystemDateTimeDay)],
			"06",		[(SystemDateTimeDay)],
			"07",		[(SystemDateTimeDay)],
			"08",		[(SystemDateTimeDay)],
			"09",		[(SystemDateTimeDay)],
			"10",		[(SystemDateTimeDay)],
			"11",		[(SystemDateTimeDay)],
			"12",		[(SystemDateTimeDay)],
			"13",		[(SystemDateTimeDay)],
			"14",		[(SystemDateTimeDay)],
			"15",		[(SystemDateTimeDay)],
			"16",		[(SystemDateTimeDay)],
			"17",		[(SystemDateTimeDay)],
			"18",		[(SystemDateTimeDay)],
			"19",		[(SystemDateTimeDay)],
			"20",		[(SystemDateTimeDay)],
			"21",		[(SystemDateTimeDay)],
			"22",		[(SystemDateTimeDay)],
			"23",		[(SystemDateTimeDay)],
			"24",		[(SystemDateTimeDay)],
			"25",		[(SystemDateTimeDay)],
			"26",		[(SystemDateTimeDay)],
			"27",		[(SystemDateTimeDay)],
			"28",		[(SystemDateTimeDay)],
			"29",		[(SystemDateTimeDay)],
			"30",		[(SystemDateTimeDay)],
			"31",		[(SystemDateTimeDay)],
		"MONTH",		[(SystemDateTimeMonth)appMenuEvt_SystemDateTimeSet],
			"01",		[(SystemDateTimeMonth)],
			"02",		[(SystemDateTimeMonth)],
			"03",		[(SystemDateTimeMonth)],
			"04",		[(SystemDateTimeMonth)],
			"05",		[(SystemDateTimeMonth)],
			"06",		[(SystemDateTimeMonth)],
			"07",		[(SystemDateTimeMonth)],
			"08",		[(SystemDateTimeMonth)],
			"09",		[(SystemDateTimeMonth)],
			"10",		[(SystemDateTimeMonth)],
			"11",		[(SystemDateTimeMonth)],
			"12",		[(SystemDateTimeMonth)],
		"YEAR",		[(SystemDateTimeYear)appMenuEvt_SystemDateTimeSet],
			"14",		[(SystemDateTimeYear)],
			"15",		[(SystemDateTimeYear)],
			"16",		[(SystemDateTimeYear)],
			"17",		[(SystemDateTimeYear)],
			"18",		[(SystemDateTimeYear)],
			"19",		[(SystemDateTimeYear)],
			"20",		[(SystemDateTimeYear)],
			"21",		[(SystemDateTimeYear)],
			"22",		[(SystemDateTimeYear)],
			"23",		[(SystemDateTimeYear)],
			"24",		[(SystemDateTimeYear)],
			"25",		[(SystemDateTimeYear)],
			"26",		[(SystemDateTimeYear)],
			"27",		[(SystemDateTimeYear)],
			"28",		[(SystemDateTimeYear)],
			"29",		[(SystemDateTimeYear)],
			"30",		[(SystemDateTimeYear)],
			"31",		[(SystemDateTimeYear)],
			"32",		[(SystemDateTimeYear)],
			"33",		[(SystemDateTimeYear)],
			"34",		[(SystemDateTimeYear)],
		"HOUR",		[(SystemDateTimeHour)appMenuEvt_SystemDateTimeSet],
			"00",		[(SystemDateTimeHour)],
			"01",		[(SystemDateTimeHour)],
			"02",		[(SystemDateTimeHour)],
			"03",		[(SystemDateTimeHour)],
			"04",		[(SystemDateTimeHour)],
			"05",		[(SystemDateTimeHour)],
			"06",		[(SystemDateTimeHour)],
			"07",		[(SystemDateTimeHour)],
			"08",		[(SystemDateTimeHour)],
			"09",		[(SystemDateTimeHour)],
			"10",		[(SystemDateTimeHour)],
			"11",		[(SystemDateTimeHour)],
			"12",		[(SystemDateTimeHour)],
			"13",		[(SystemDateTimeHour)],
			"14",		[(SystemDateTimeHour)],
			"15",		[(SystemDateTimeHour)],
			"16",		[(SystemDateTimeHour)],
			"17",		[(SystemDateTimeHour)],
			"18",		[(SystemDateTimeHour)],
			"19",		[(SystemDateTimeHour)],
			"20",		[(SystemDateTimeHour)],
			"21",		[(SystemDateTimeHour)],
			"22",		[(SystemDateTimeHour)],
			"23",		[(SystemDateTimeHour)],
		"MINUTE",		[(SystemDateTimeMinute)appMenuEvt_SystemDateTimeSet],
			"00",		[(SystemDateTimeMinute)],
			"01",		[(SystemDateTimeMinute)],
			"02",		[(SystemDateTimeMinute)],
			"03",		[(SystemDateTimeMinute)],
			"04",		[(SystemDateTimeMinute)],
			"05",		[(SystemDateTimeMinute)],
			"06",		[(SystemDateTimeMinute)],
			"07",		[(SystemDateTimeMinute)],
			"08",		[(SystemDateTimeMinute)],
			"09",		[(SystemDateTimeMinute)],
			"10",		[(SystemDateTimeMinute)],
			"11",		[(SystemDateTimeMinute)],
			"12",		[(SystemDateTimeMinute)],
			"13",		[(SystemDateTimeMinute)],
			"14",		[(SystemDateTimeMinute)],
			"15",		[(SystemDateTimeMinute)],
			"16",		[(SystemDateTimeMinute)],
			"17",		[(SystemDateTimeMinute)],
			"18",		[(SystemDateTimeMinute)],
			"19",		[(SystemDateTimeMinute)],
			"20",		[(SystemDateTimeMinute)],
			"21",		[(SystemDateTimeMinute)],
			"22",		[(SystemDateTimeMinute)],
			"23",		[(SystemDateTimeMinute)],
			"24",		[(SystemDateTimeMinute)],
			"25",		[(SystemDateTimeMinute)],
			"26",		[(SystemDateTimeMinute)],
			"27",		[(SystemDateTimeMinute)],
			"28",		[(SystemDateTimeMinute)],
			"29",		[(SystemDateTimeMinute)],
			"30",		[(SystemDateTimeMinute)],
			"31",		[(SystemDateTimeMinute)],
			"32",		[(SystemDateTimeMinute)],
			"33",		[(SystemDateTimeMinute)],
			"34",		[(SystemDateTimeMinute)],
			"35",		[(SystemDateTimeMinute)],
			"36",		[(SystemDateTimeMinute)],
			"37",		[(SystemDateTimeMinute)],
			"38",		[(SystemDateTimeMinute)],
			"39",		[(SystemDateTimeMinute)],
			"40",		[(SystemDateTimeMinute)],
			"41",		[(SystemDateTimeMinute)],
			"42",		[(SystemDateTimeMinute)],
			"43",		[(SystemDateTimeMinute)],
			"44",		[(SystemDateTimeMinute)],
			"45",		[(SystemDateTimeMinute)],
			"46",		[(SystemDateTimeMinute)],
			"47",		[(SystemDateTimeMinute)],
			"48",		[(SystemDateTimeMinute)],
			"49",		[(SystemDateTimeMinute)],
			"50",		[(SystemDateTimeMinute)],
			"51",		[(SystemDateTimeMinute)],
			"52",		[(SystemDateTimeMinute)],
			"53",		[(SystemDateTimeMinute)],
			"54",		[(SystemDateTimeMinute)],
			"55",		[(SystemDateTimeMinute)],
			"56",		[(SystemDateTimeMinute)],
			"57",		[(SystemDateTimeMinute)],
			"58",		[(SystemDateTimeMinute)],
			"59",		[(SystemDateTimeMinute)],
		"SECOND",		[(SystemDateTimeSecond)appMenuEvt_SystemDateTimeSet],
			"00",		[(SystemDateTimeSecond)],
			"01",		[(SystemDateTimeSecond)],
			"02",		[(SystemDateTimeSecond)],
			"03",		[(SystemDateTimeSecond)],
			"04",		[(SystemDateTimeSecond)],
			"05",		[(SystemDateTimeSecond)],
			"06",		[(SystemDateTimeSecond)],
			"07",		[(SystemDateTimeSecond)],
			"08",		[(SystemDateTimeSecond)],
			"09",		[(SystemDateTimeSecond)],
			"10",		[(SystemDateTimeSecond)],
			"11",		[(SystemDateTimeSecond)],
			"12",		[(SystemDateTimeSecond)],
			"13",		[(SystemDateTimeSecond)],
			"14",		[(SystemDateTimeSecond)],
			"15",		[(SystemDateTimeSecond)],
			"16",		[(SystemDateTimeSecond)],
			"17",		[(SystemDateTimeSecond)],
			"18",		[(SystemDateTimeSecond)],
			"19",		[(SystemDateTimeSecond)],
			"20",		[(SystemDateTimeSecond)],
			"21",		[(SystemDateTimeSecond)],
			"22",		[(SystemDateTimeSecond)],
			"23",		[(SystemDateTimeSecond)],
			"24",		[(SystemDateTimeSecond)],
			"25",		[(SystemDateTimeSecond)],
			"26",		[(SystemDateTimeSecond)],
			"27",		[(SystemDateTimeSecond)],
			"28",		[(SystemDateTimeSecond)],
			"29",		[(SystemDateTimeSecond)],
			"30",		[(SystemDateTimeSecond)],
			"31",		[(SystemDateTimeSecond)],
			"32",		[(SystemDateTimeSecond)],
			"33",		[(SystemDateTimeSecond)],
			"34",		[(SystemDateTimeSecond)],
			"35",		[(SystemDateTimeSecond)],
			"36",		[(SystemDateTimeSecond)],
			"37",		[(SystemDateTimeSecond)],
			"38",		[(SystemDateTimeSecond)],
			"39",		[(SystemDateTimeSecond)],
			"40",		[(SystemDateTimeSecond)],
			"41",		[(SystemDateTimeSecond)],
			"42",		[(SystemDateTimeSecond)],
			"43",		[(SystemDateTimeSecond)],
			"44",		[(SystemDateTimeSecond)],
			"45",		[(SystemDateTimeSecond)],
			"46",		[(SystemDateTimeSecond)],
			"47",		[(SystemDateTimeSecond)],
			"48",		[(SystemDateTimeSecond)],
			"49",		[(SystemDateTimeSecond)],
			"50",		[(SystemDateTimeSecond)],
			"51",		[(SystemDateTimeSecond)],
			"52",		[(SystemDateTimeSecond)],
			"53",		[(SystemDateTimeSecond)],
			"54",		[(SystemDateTimeSecond)],
			"55",		[(SystemDateTimeSecond)],
			"56",		[(SystemDateTimeSecond)],
			"57",		[(SystemDateTimeSecond)],
			"58",		[(SystemDateTimeSecond)],
			"59",		[(SystemDateTimeSecond)],
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_SystemDateTimeSet],
		"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_SystemDateTimeSet],
[MARK]MENU_MARK_RF_REMOTER:
	"REMOTER",		"system_remoter.bmp",		[appMenuAct_SystemRemoter(SystemRemoter)],
		"SCANNING",		"system_remoter_scanning.bmp",		[(SystemRemoter)appMenuEvt_SystemRemoterSet],
		"OFF",		"scdv_off.bmp",		[(SystemRemoter)appMenuEvt_SystemRemoterSet],
	"FREQUENCY",		"system_frequnecy.bmp",		[appMenuAct_SystemFrequnecy(SystemFrequnecy)],
		"50HZ",		"system_frequnecy_50HZ.bmp",		[(SystemFrequnecy)appMenuEvt_SystemFrequnecySet],
		"60HZ",		"system_frequnecy_60HZ.bmp",		[(SystemFrequnecy)appMenuEvt_SystemFrequnecySet],
	"FORMAT",		"system_format.bmp",		[appMenuAct_SystemFormat()],
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_SystemFormatSet],
		"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_SystemFormatSet],
	"DEFAULT",		"system_default.bmp",		[appMenuAct_SystemDefault()],
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_SystemDefaultSet],
		"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_SystemDefaultSet],
[MARK]MENU_MARK_SYSTEM2_WIFI_PW:
	"WIFI PASSWORD...",		"system_wifi_password.bmp",		[appMenuAct_SystemWifiPassword()appMenuEvt_SystemWifiPasswordInit],
		"BIT0",		[(SystemWifiPassword00)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword00)],
			"1",		[(SystemWifiPassword00)],
			"2",		[(SystemWifiPassword00)],
			"3",		[(SystemWifiPassword00)],
			"4",		[(SystemWifiPassword00)],
			"5",		[(SystemWifiPassword00)],
			"6",		[(SystemWifiPassword00)],
			"7",		[(SystemWifiPassword00)],
			"8",		[(SystemWifiPassword00)],
			"9",		[(SystemWifiPassword00)],
		"BIT1",		[(SystemWifiPassword01)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword01)],
			"1",		[(SystemWifiPassword01)],
			"2",		[(SystemWifiPassword01)],
			"3",		[(SystemWifiPassword01)],
			"4",		[(SystemWifiPassword01)],
			"5",		[(SystemWifiPassword01)],
			"6",		[(SystemWifiPassword01)],
			"7",		[(SystemWifiPassword01)],
			"8",		[(SystemWifiPassword01)],
			"9",		[(SystemWifiPassword01)],
		"BIT2",		[(SystemWifiPassword02)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword02)],
			"1",		[(SystemWifiPassword02)],
			"2",		[(SystemWifiPassword02)],
			"3",		[(SystemWifiPassword02)],
			"4",		[(SystemWifiPassword02)],
			"5",		[(SystemWifiPassword02)],
			"6",		[(SystemWifiPassword02)],
			"7",		[(SystemWifiPassword02)],
			"8",		[(SystemWifiPassword02)],
			"9",		[(SystemWifiPassword02)],
		"BIT3",		[(SystemWifiPassword03)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword03)],
			"1",		[(SystemWifiPassword03)],
			"2",		[(SystemWifiPassword03)],
			"3",		[(SystemWifiPassword03)],
			"4",		[(SystemWifiPassword03)],
			"5",		[(SystemWifiPassword03)],
			"6",		[(SystemWifiPassword03)],
			"7",		[(SystemWifiPassword03)],
			"8",		[(SystemWifiPassword03)],
			"9",		[(SystemWifiPassword03)],
		"BIT4",		[(SystemWifiPassword04)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword04)],
			"1",		[(SystemWifiPassword04)],
			"2",		[(SystemWifiPassword04)],
			"3",		[(SystemWifiPassword04)],
			"4",		[(SystemWifiPassword04)],
			"5",		[(SystemWifiPassword04)],
			"6",		[(SystemWifiPassword04)],
			"7",		[(SystemWifiPassword04)],
			"8",		[(SystemWifiPassword04)],
			"9",		[(SystemWifiPassword04)],
		"BIT5",		[(SystemWifiPassword05)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword05)],
			"1",		[(SystemWifiPassword05)],
			"2",		[(SystemWifiPassword05)],
			"3",		[(SystemWifiPassword05)],
			"4",		[(SystemWifiPassword05)],
			"5",		[(SystemWifiPassword05)],
			"6",		[(SystemWifiPassword05)],
			"7",		[(SystemWifiPassword05)],
			"8",		[(SystemWifiPassword05)],
			"9",		[(SystemWifiPassword05)],
		"BIT6",		[(SystemWifiPassword06)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword06)],
			"1",		[(SystemWifiPassword06)],
			"2",		[(SystemWifiPassword06)],
			"3",		[(SystemWifiPassword06)],
			"4",		[(SystemWifiPassword06)],
			"5",		[(SystemWifiPassword06)],
			"6",		[(SystemWifiPassword06)],
			"7",		[(SystemWifiPassword06)],
			"8",		[(SystemWifiPassword06)],
			"9",		[(SystemWifiPassword06)],
		"BIT7",		[(SystemWifiPassword07)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword07)],
			"1",		[(SystemWifiPassword07)],
			"2",		[(SystemWifiPassword07)],
			"3",		[(SystemWifiPassword07)],
			"4",		[(SystemWifiPassword07)],
			"5",		[(SystemWifiPassword07)],
			"6",		[(SystemWifiPassword07)],
			"7",		[(SystemWifiPassword07)],
			"8",		[(SystemWifiPassword07)],
			"9",		[(SystemWifiPassword07)],
		"BIT8",		[(SystemWifiPassword08)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword08)],
			"1",		[(SystemWifiPassword08)],
			"2",		[(SystemWifiPassword08)],
			"3",		[(SystemWifiPassword08)],
			"4",		[(SystemWifiPassword08)],
			"5",		[(SystemWifiPassword08)],
			"6",		[(SystemWifiPassword08)],
			"7",		[(SystemWifiPassword08)],
			"8",		[(SystemWifiPassword08)],
			"9",		[(SystemWifiPassword08)],
		"BIT9",		[(SystemWifiPassword09)appMenuEvt_SystemWifiPasswordSet],
			"0",		[(SystemWifiPassword09)],
			"1",		[(SystemWifiPassword09)],
			"2",		[(SystemWifiPassword09)],
			"3",		[(SystemWifiPassword09)],
			"4",		[(SystemWifiPassword09)],
			"5",		[(SystemWifiPassword09)],
			"6",		[(SystemWifiPassword09)],
			"7",		[(SystemWifiPassword09)],
			"8",		[(SystemWifiPassword09)],
			"9",		[(SystemWifiPassword09)],
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_SystemWifiPasswordSet],
		"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_SystemWifiPasswordSet],
	"VERSION",		"system_version.bmp",		[appMenuAct_SystemVersion()appMenuEvt_SystemVersionInit],
		"VERSION",		[()appMenuEvt_SystemVersionSet],
	"EXIT",		"scdv_exit.bmp",		[appMenuAct_SystemExit()appMenuEvt_SystemExitSet],
[MARK]MENU_MARK_MENU_EXIT:
"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_ModeMenuExit],
[MARK]MENU_MARK_DELETE:
"DELETE",		"scdv_delete_mode.bmp",		[()appMenuEvt_ModeDelete],
	"ALL",		"scdv_delete_all.bmp",
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_DeleteAllOKSet],
		"EXIT",		"scdv_exit.bmp",
	"ONE",		"scdv_delete_one.bmp",
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_DeleteLastOKSet],
		"EXIT",		"scdv_exit.bmp",
[MARK]MENU_MARK_DELETE_EXIT:
	"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_DeleteMenuExit],
[MARK]MENU_MARK_DELETE_LOOP:
"DEL LOOP",		"scdv_delete_loop.bmp",		[()appMenuEvt_ModeDeleteLoop],
	"ALL",		"scdv_delete_all.bmp",
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_DeleteLoopAllOKSet],
		"EXIT",		"scdv_exit.bmp",
	"ONE",		"scdv_delete_one.bmp",
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_DeleteLoopLastOKSet],
		"EXIT",		"scdv_exit.bmp",
[MARK]MENU_MARK_DELETE_LOOP_EXIT:
	"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_DeleteLoopMenuExit],
[MARK]MENU_MARK_DELETE_EVENT:
"DEL EVENT",		"scdv_delete_event.bmp",		[()appMenuEvt_ModeDeleteEvent],
	"ALL",		"scdv_delete_all.bmp",
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_DeleteEventAllOKSet],
		"EXIT",		"scdv_exit.bmp",
	"ONE",		"scdv_delete_one.bmp",
		"OK",		"scdv_ok.bmp",		[()appMenuEvt_DeleteEventLastOKSet],
		"EXIT",		"scdv_exit.bmp",
[MARK]MENU_MARK_DELETE_EVENT_EXIT:
	"EXIT",		"scdv_exit.bmp",		[()appMenuEvt_DeleteEventMenuExit],
[MARK]MENU_MARK_SCDV_PB_SELECT:
"PB SELECT",
	"PB SELECT",
		"PB SELECT",		[(ScdvPbFileType)],
[MARK]MENU_MARK_SCDV_PB_VIDEO:
			"VIDEO",		[(ScdvPbFileType)appMenuEvt_ScdvPbFileTypeSet],
			"PHOTO",		[(ScdvPbFileType)appMenuEvt_ScdvPbFileTypeSet],
			"EVENT",		[appMenuAct_ScdvPbFileType(ScdvPbFileType)appMenuEvt_ScdvPbFileTypeSet],
[MARK]MENU_MARK_STILL:
"Still Record",		"mode_still.bmp",		[()appMenuEvt_ModeStill],
	"Resolution",		[appMenuAct_ImageSize(ImageSize)appMenuEvt_FisrstItemProcess],
		"10M",		"resolution_10m.bmp",		[(ImageSize)appMenuEvt_ImageSizeSet],
		"8M",		"resolution_8m.bmp",		[(ImageSize)appMenuEvt_ImageSizeSet],
		"6M",		"resolution_6m.bmp",		[(ImageSize)appMenuEvt_ImageSizeSet],
		"3M",		"resolution_3m.bmp",		[(ImageSize)appMenuEvt_ImageSizeSet],
		"2M",		"resolution_2m_16_9.bmp",		[(ImageSize)appMenuEvt_ImageSizeSet],
		"VGA",		"resolution_vga.bmp",		[(ImageSize)appMenuEvt_ImageSizeSet],
		"Custom",		"wb_custom.bmp",		[(WBMode)appMenuEvt_WBModeSet],
	"Driver Mode",		[(DriverMode)],
		"Off",		"off.bmp",		[(DriverMode)appMenuEvt_DriverModeSet],
		"2S",		"selftimer_2sec.bmp",		[(DriverMode)appMenuEvt_DriverModeSet],
		"10S",		"selftimer_10sec.bmp",		[(DriverMode)appMenuEvt_DriverModeSet],
		"Double",		"double.bmp",		[(DriverMode)appMenuEvt_DriverModeSet],
	"Photo Burst",		[(PhotoBurst)appMenuEvt_LastItemProcess],
		"off",		[(PhotoBurst)appMenuEvt_PhotoBurstSet],
		"10 fps",		[(PhotoBurst)appMenuEvt_PhotoBurstSet],
		"20 fps",		[(PhotoBurst)appMenuEvt_PhotoBurstSet],
		"30 fps",		[(PhotoBurst)appMenuEvt_PhotoBurstSet],
[MARK]MENU_MARK_VIDEO:
"VideoMenu",		"mode_video.bmp",		[()appMenuEvt_ModeVideo],
	"Movie Size",		[(VideoSize)appMenuEvt_FisrstItemProcess],
		"1080P(30fps)",		"movie_size_1080p.bmp",		[(VideoSize)appMenuEvt_VideoSizeSet],
		"720P(30fps)",		"movie_size_720p.bmp",		[(VideoSize)appMenuEvt_VideoSizeSet],
		"720P(60fps)",		"movie_size_720p.bmp",		[(VideoSize)appMenuEvt_VideoSizeSet],
	"Video Quality",		[(VideoQuality)],
		"Super Fine",		"quality_super_fine.bmp",		[(VideoQuality)appMenuEvt_VideoQualitySet],
		"Fine",		"quality_fine.bmp",		[(VideoQuality)appMenuEvt_VideoQualitySet],
		"Normal",		"quality.bmp",		[(VideoQuality)appMenuEvt_VideoQualitySet],
	"Seamless",		[(Seamless)],
		"Off",		"off.bmp",		[(Seamless)appMenuEvt_SeamlessSet],
		"1 Min",		"1min.bmp",		[(Seamless)appMenuEvt_SeamlessSet],
		"3 Min",		"3min.bmp",		[(Seamless)appMenuEvt_SeamlessSet],
		"5 Min",		"5min.bmp",		[(Seamless)appMenuEvt_SeamlessSet],
	"White Balance",		[(WBMode)],
		"Auto",		"wb_auto.bmp",		[(WBMode)appMenuEvt_VideoWBModeSet],
		"Daylight",		"wb_daylight.bmp",		[(WBMode)appMenuEvt_VideoWBModeSet],
		"Cloudy",		"wb_cloudy.bmp",		[(WBMode)appMenuEvt_VideoWBModeSet],
		"Tungsten",		"wb_tungsten.bmp",		[(WBMode)appMenuEvt_VideoWBModeSet],
		"Fluor H",		"wb_fluorescent_h.bmp",		[(WBMode)appMenuEvt_VideoWBModeSet],
		"Custom",		"wb_custom.bmp",		[(WBMode)appMenuEvt_VideoWBModeSet],
	"WDR",		[(WDRMode)],
		"Off",		"off.bmp",		[(WDRMode)appMenuEvt_WDRModeSet],
		"On",		"on.bmp",		[(WDRMode)appMenuEvt_WDRModeSet],
	"Motion Detect",		[(MotionDetect)],
		"Off",		"off.bmp",		[(MotionDetect)appMenuEvt_MDModeSet],
		"On",		"on.bmp",		[(MotionDetect)appMenuEvt_MDModeSet],
	"Date Stamp",		[(VideoStampMode)appMenuEvt_LastItemProcess],
		"Off",		"off.bmp",		[(VideoStampMode)appMenuEvt_VideoStampModeSet],
		"Date",		"print_date.bmp",		[(VideoStampMode)appMenuEvt_VideoStampModeSet],
		"Date&Time",		"print_dateandtime.bmp",		[(VideoStampMode)appMenuEvt_VideoStampModeSet],
[MARK]MENU_MARK_PLAYBACK:
"Playback",		"mode_playback.bmp",		[()appMenuEvt_ModePlayback],
	"Protect",		[()appMenuEvt_FisrstItemProcess],
		"Single",		[(selImgProtect)appMenuEvt_PbFileProtect],
			"Yes",
			"No",
		"Protect All",		[(selImgProtect)appMenuEvt_PbFileProtect],
			"Yes",
			"No",
		"Unprotect All",		[(selImgProtect)appMenuEvt_PbFileProtect],
			"Yes",
			"No",
	"Delete...",		[()appMenuEvt_LastItemProcess],
		"Single",		[(selImgDelete)appMenuEvt_PbFileDelete],
			"Yes",
			"No",
		"All",		[(selImgDelete)appMenuEvt_PbFileDelete],
			"Yes",
			"No",
[MARK]MENU_MARK_SETUP:
"Setup",		"mode_setup.bmp",		[()appMenuEvt_ModeSetup],
	"Sounds...",		[()appMenuEvt_SoundInit],
		"Beep",		[(BeepSound)appMenuEvt_SoundSet],
			"Off",		[(BeepSound)],
			"On",		[(BeepSound)],
		"Volume",		[(Volume)appMenuEvt_SoundSet],
			"0",		[(Volume)],
			"1",		[(Volume)],
			"2",		[(Volume)],
			"3",		[(Volume)],
		"Voice Rec",		[(VoiceRec)appMenuEvt_SoundSet],
			"Off",		[(VoiceRec)],
			"On",		[(VoiceRec)],
	"Power Save",		[(SleepTime)],
		"OFF",		"off.bmp",		[(SleepTime)appMenuEvt_SleepTimeSet],
		"1min.",		"1min.bmp",		[(SleepTime)appMenuEvt_SleepTimeSet],
		"3min.",		"3min.bmp",		[(SleepTime)appMenuEvt_SleepTimeSet],
		"5min.",		"5min.bmp",		[(SleepTime)appMenuEvt_SleepTimeSet],
	"Date & Time...",		[()appMenuEvt_RTCInit],
		"Year",		[(rtcYear)appMenuEvt_RTCSet],
			"2000",		[(rtcYear)],
			"2001",		[(rtcYear)],
			"2002",		[(rtcYear)],
			"2003",		[(rtcYear)],
			"2004",		[(rtcYear)],
			"2005",		[(rtcYear)],
			"2006",		[(rtcYear)],
			"2007",		[(rtcYear)],
			"2008",		[(rtcYear)],
			"2009",		[(rtcYear)],
			"2010",		[(rtcYear)],
			"2011",		[(rtcYear)],
			"2012",		[(rtcYear)],
			"2013",		[(rtcYear)],
			"2014",		[(rtcYear)],
			"2015",		[(rtcYear)],
			"2016",		[(rtcYear)],
			"2017",		[(rtcYear)],
			"2018",		[(rtcYear)],
			"2019",		[(rtcYear)],
			"2020",		[(rtcYear)],
			"2021",		[(rtcYear)],
			"2022",		[(rtcYear)],
			"2023",		[(rtcYear)],
			"2024",		[(rtcYear)],
			"2025",		[(rtcYear)],
			"2026",		[(rtcYear)],
			"2027",		[(rtcYear)],
			"2028",		[(rtcYear)],
			"2029",		[(rtcYear)],
			"2030",		[(rtcYear)],
		"Month",		[(rtcMonth)appMenuEvt_RTCSet],
			"01",		[(rtcMonth)],
			"02",		[(rtcMonth)],
			"03",		[(rtcMonth)],
			"04",		[(rtcMonth)],
			"05",		[(rtcMonth)],
			"06",		[(rtcMonth)],
			"07",		[(rtcMonth)],
			"08",		[(rtcMonth)],
			"09",		[(rtcMonth)],
			"10",		[(rtcMonth)],
			"11",		[(rtcMonth)],
			"12",		[(rtcMonth)],
		"Day",		[(rtcDay)appMenuEvt_RTCSet],
			"01",		[(rtcDay)],
			"02",		[(rtcDay)],
			"03",		[(rtcDay)],
			"04",		[(rtcDay)],
			"05",		[(rtcDay)],
			"06",		[(rtcDay)],
			"07",		[(rtcDay)],
			"08",		[(rtcDay)],
			"09",		[(rtcDay)],
			"10",		[(rtcDay)],
			"11",		[(rtcDay)],
			"12",		[(rtcDay)],
			"13",		[(rtcDay)],
			"14",		[(rtcDay)],
			"15",		[(rtcDay)],
			"16",		[(rtcDay)],
			"17",		[(rtcDay)],
			"18",		[(rtcDay)],
			"19",		[(rtcDay)],
			"20",		[(rtcDay)],
			"21",		[(rtcDay)],
			"22",		[(rtcDay)],
			"23",		[(rtcDay)],
			"24",		[(rtcDay)],
			"25",		[(rtcDay)],
			"26",		[(rtcDay)],
			"27",		[(rtcDay)],
			"28",		[(rtcDay)],
			"29",		[(rtcDay)],
			"30",		[(rtcDay)],
			"31",		[(rtcDay)],
		"Hour",		[(rtcHour)appMenuEvt_RTCSet],
			"00",		[(rtcHour)],
			"01",		[(rtcHour)],
			"02",		[(rtcHour)],
			"03",		[(rtcHour)],
			"04",		[(rtcHour)],
			"05",		[(rtcHour)],
			"06",		[(rtcHour)],
			"07",		[(rtcHour)],
			"08",		[(rtcHour)],
			"09",		[(rtcHour)],
			"10",		[(rtcHour)],
			"11",		[(rtcHour)],
			"12",		[(rtcHour)],
			"13",		[(rtcHour)],
			"14",		[(rtcHour)],
			"15",		[(rtcHour)],
			"16",		[(rtcHour)],
			"17",		[(rtcHour)],
			"18",		[(rtcHour)],
			"19",		[(rtcHour)],
			"20",		[(rtcHour)],
			"21",		[(rtcHour)],
			"22",		[(rtcHour)],
			"23",		[(rtcHour)],
		"Minute",		[(rtcMinute)appMenuEvt_RTCSet],
			"00",		[(rtcMinute)],
			"01",		[(rtcMinute)],
			"02",		[(rtcMinute)],
			"03",		[(rtcMinute)],
			"04",		[(rtcMinute)],
			"05",		[(rtcMinute)],
			"06",		[(rtcMinute)],
			"07",		[(rtcMinute)],
			"08",		[(rtcMinute)],
			"09",		[(rtcMinute)],
			"10",		[(rtcMinute)],
			"11",		[(rtcMinute)],
			"12",		[(rtcMinute)],
			"13",		[(rtcMinute)],
			"14",		[(rtcMinute)],
			"15",		[(rtcMinute)],
			"16",		[(rtcMinute)],
			"17",		[(rtcMinute)],
			"18",		[(rtcMinute)],
			"19",		[(rtcMinute)],
			"20",		[(rtcMinute)],
			"21",		[(rtcMinute)],
			"22",		[(rtcMinute)],
			"23",		[(rtcMinute)],
			"24",		[(rtcMinute)],
			"25",		[(rtcMinute)],
			"26",		[(rtcMinute)],
			"27",		[(rtcMinute)],
			"28",		[(rtcMinute)],
			"29",		[(rtcMinute)],
			"30",		[(rtcMinute)],
			"31",		[(rtcMinute)],
			"32",		[(rtcMinute)],
			"33",		[(rtcMinute)],
			"34",		[(rtcMinute)],
			"35",		[(rtcMinute)],
			"36",		[(rtcMinute)],
			"37",		[(rtcMinute)],
			"38",		[(rtcMinute)],
			"39",		[(rtcMinute)],
			"40",		[(rtcMinute)],
			"41",		[(rtcMinute)],
			"42",		[(rtcMinute)],
			"43",		[(rtcMinute)],
			"44",		[(rtcMinute)],
			"45",		[(rtcMinute)],
			"46",		[(rtcMinute)],
			"47",		[(rtcMinute)],
			"48",		[(rtcMinute)],
			"49",		[(rtcMinute)],
			"50",		[(rtcMinute)],
			"51",		[(rtcMinute)],
			"52",		[(rtcMinute)],
			"53",		[(rtcMinute)],
			"54",		[(rtcMinute)],
			"55",		[(rtcMinute)],
			"56",		[(rtcMinute)],
			"57",		[(rtcMinute)],
			"58",		[(rtcMinute)],
			"59",		[(rtcMinute)],
		"TimeStyle",		[(DateStyle)appMenuEvt_RTCSet],
			"YY/MM/DD",		[(DateStyle)],
			"MM/DD/YY",		[(DateStyle)],
			"DD/MM/YY",		[(DateStyle)],
	"Language",		[(Language)],
		"English",		"language_en.bmp",		[(Language)appMenuEvt_LanguageSet],
		"",		"language_cs.bmp",		[(Language)appMenuEvt_LanguageSet],
		"",		"language_ct.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Français",		"language_fr.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Nederlands",		"language_nl.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Español",		"language_es.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Italiano",		"language_it.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Português",		"language_pt.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Deutsch",		"language_de.bmp",		[(Language)appMenuEvt_LanguageSet],
		"estina",		"language_ce.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Magyar",		"language_hu.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Viet",		"language_vn.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Polski",		"language_pl.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Türk",		"language_tr.bmp",		[(Language)appMenuEvt_LanguageSet],
		"",		"language_ru.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Svenska",		"language_se.bmp",		[(Language)appMenuEvt_LanguageSet],
		"",		"language_gr.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Român",		"language_ro.bmp",		[(Language)appMenuEvt_LanguageSet],
		"Malay",		"language_ml.bmp",		[(Language)appMenuEvt_LanguageSet],
		"",		"language_jp.bmp",		[(Language)appMenuEvt_LanguageSet],
		"",		"language_kr.bmp",		[(Language)appMenuEvt_LanguageSet],
		"\x08",		"language_th.bmp",		[(Language)appMenuEvt_LanguageSet],
		"\x09",		"language_ae.bmp",		[(Language)appMenuEvt_LanguageSet],
		"\x0a",		"LANGUAGE_IN.bmp",		[(Language)appMenuEvt_LanguageSet],
		"\x0b",		"language_bd.bmp",		[(Language)appMenuEvt_LanguageSet],
	"TV Out",		[(TVMode)],
		"NTSC",		"tv_mode_ntsc.bmp",		[(TVMode)appMenuEvt_TVModeSet],
		"PAL",		"tv_mode_pal.bmp",		[(TVMode)appMenuEvt_TVModeSet],
	"G_Sensor",		[(G_Sensor)],
		"Off",		[(G_Sensor)appMenuEvt_G_SensorSet],
		"Low",		[(G_Sensor)appMenuEvt_G_SensorSet],
		"Normal",		[(G_Sensor)appMenuEvt_G_SensorSet],
		"High",		[(G_Sensor)appMenuEvt_G_SensorSet],
		"Sport",		[(G_Sensor)appMenuEvt_G_SensorSet],
	"Light Freq",		[(LightFreq)],
		"50HZ",		[(LightFreq)appMenuEvt_LightFreqSet],
		"60HZ",		[(LightFreq)appMenuEvt_LightFreqSet],
	"GPS",		[(GPS)],
		"Off",		[(GPS)appMenuEvt_GPSSet],
		"On",		[(GPS)appMenuEvt_GPSSet],
	"Water Mark",		[(WaterMark)],
		"Off",		[(WaterMark)appMenuEvt_WaterMarkSet],
		"On",		[(WaterMark)appMenuEvt_WaterMarkSet],
	"LOGO Mark",		[(LOGOMark)],
		"Off",		[(LOGOMark)appMenuEvt_LOGOMarkSet],
		"On",		[(LOGOMark)appMenuEvt_LOGOMarkSet],
	"Stabilizer",		[(Stabilizer)],
		"Off",		[(Stabilizer)appMenuEvt_StabilizerSet],
		"On",		[(Stabilizer)appMenuEvt_StabilizerSet],
	"Invert Mode",		[(InvertMode)],
		"Off",		[(InvertMode)appMenuEvt_InvertModeSet],
		"On",		[(InvertMode)appMenuEvt_InvertModeSet],
	"Collision Detection",		[(CollisionDetection)],
		"Off",		[(CollisionDetection)appMenuEvt_CollisionDetectionSet],
		"On",		[(CollisionDetection)appMenuEvt_CollisionDetectionSet],
	"Time Zones",		[(TimeZones)],
		"-12",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-11",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-10",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-9",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-8",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-7",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-6",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-5",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-4",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-3",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-2",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"-1",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+0",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+1",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+2",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+3",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+4",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+5",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+6",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+7",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+8",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+9",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+10",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+11",		[(TimeZones)appMenuEvt_TimeZonesSet],
		"+12",		[(TimeZones)appMenuEvt_TimeZonesSet],
	"System",		[(SystemMode)],
		"FactoryReset",		[(SystemMode)appMenuEvt_SystemModeSet],
			"Yes",
			"No",
		"SystemInfo",		[(SystemMode)appMenuEvt_SystemModeSet],
		"CardInfo",		[(SystemMode)appMenuEvt_SystemModeSet],
		"GSVinfo",		[(SystemMode)appMenuEvt_SystemModeSet],
	"Format...",
		"Yes",		[()appMenuEvt_Format],
		"No",		[()appMenuEvt_Format],
	"WIFI Password",		[()appMenuEvt_WIFIPasswordInit],
		"num7",		[(WIFIPassword_7)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_7)],
			"1",		[(WIFIPassword_7)],
			"2",		[(WIFIPassword_7)],
			"3",		[(WIFIPassword_7)],
			"4",		[(WIFIPassword_7)],
			"5",		[(WIFIPassword_7)],
			"6",		[(WIFIPassword_7)],
			"7",		[(WIFIPassword_7)],
			"8",		[(WIFIPassword_7)],
			"9",		[(WIFIPassword_7)],
		"num6",		[(WIFIPassword_6)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_6)],
			"1",		[(WIFIPassword_6)],
			"2",		[(WIFIPassword_6)],
			"3",		[(WIFIPassword_6)],
			"4",		[(WIFIPassword_6)],
			"5",		[(WIFIPassword_6)],
			"6",		[(WIFIPassword_6)],
			"7",		[(WIFIPassword_6)],
			"8",		[(WIFIPassword_6)],
			"9",		[(WIFIPassword_6)],
		"num5",		[(WIFIPassword_5)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_5)],
			"1",		[(WIFIPassword_5)],
			"2",		[(WIFIPassword_5)],
			"3",		[(WIFIPassword_5)],
			"4",		[(WIFIPassword_5)],
			"5",		[(WIFIPassword_5)],
			"6",		[(WIFIPassword_5)],
			"7",		[(WIFIPassword_5)],
			"8",		[(WIFIPassword_5)],
			"9",		[(WIFIPassword_5)],
		"num4",		[(WIFIPassword_4)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_4)],
			"1",		[(WIFIPassword_4)],
			"2",		[(WIFIPassword_4)],
			"3",		[(WIFIPassword_4)],
			"4",		[(WIFIPassword_4)],
			"5",		[(WIFIPassword_4)],
			"6",		[(WIFIPassword_4)],
			"7",		[(WIFIPassword_4)],
			"8",		[(WIFIPassword_4)],
			"9",		[(WIFIPassword_4)],
		"num3",		[(WIFIPassword_3)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_3)],
			"1",		[(WIFIPassword_3)],
			"2",		[(WIFIPassword_3)],
			"3",		[(WIFIPassword_3)],
			"4",		[(WIFIPassword_3)],
			"5",		[(WIFIPassword_3)],
			"6",		[(WIFIPassword_3)],
			"7",		[(WIFIPassword_3)],
			"8",		[(WIFIPassword_3)],
			"9",		[(WIFIPassword_3)],
		"num2",		[(WIFIPassword_2)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_2)],
			"1",		[(WIFIPassword_2)],
			"2",		[(WIFIPassword_2)],
			"3",		[(WIFIPassword_2)],
			"4",		[(WIFIPassword_2)],
			"5",		[(WIFIPassword_2)],
			"6",		[(WIFIPassword_2)],
			"7",		[(WIFIPassword_2)],
			"8",		[(WIFIPassword_2)],
			"9",		[(WIFIPassword_2)],
		"num1",		[(WIFIPassword_1)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_1)],
			"1",		[(WIFIPassword_1)],
			"2",		[(WIFIPassword_1)],
			"3",		[(WIFIPassword_1)],
			"4",		[(WIFIPassword_1)],
			"5",		[(WIFIPassword_1)],
			"6",		[(WIFIPassword_1)],
			"7",		[(WIFIPassword_1)],
			"8",		[(WIFIPassword_1)],
			"9",		[(WIFIPassword_1)],
		"num0",		[(WIFIPassword_0)appMenuEvt_WIFIPasswordSet],
			"0",		[(WIFIPassword_0)],
			"1",		[(WIFIPassword_0)],
			"2",		[(WIFIPassword_0)],
			"3",		[(WIFIPassword_0)],
			"4",		[(WIFIPassword_0)],
			"5",		[(WIFIPassword_0)],
			"6",		[(WIFIPassword_0)],
			"7",		[(WIFIPassword_0)],
			"8",		[(WIFIPassword_0)],
			"9",		[(WIFIPassword_0)],
	"TimeLapse",		[(TimeLapse)appMenuEvt_LastItemProcess],
		"off",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"10 sec",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"20 sec",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"30 sec",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"1 min",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"5 min",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"10 min",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"30 min",		[(TimeLapse)appMenuEvt_TimeLapseSet],
		"60 min",		[(TimeLapse)appMenuEvt_TimeLapseSet],
[MARK]MENU_MARK_SCENEMODE:
"SceneMode",
[MARK]MENU_MARK_SCENEMODEITEM:
	"Program",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Movie",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Smile Catch",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Shake-free",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Landscape",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Backlight",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Nightscene",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Building",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Kids",		[(SceneMode)appMenuEvt_SceneModeSet],
	"High ISO Portrait",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Food",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Text",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Snow",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Fireworks",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Sunset",		[(SceneMode)appMenuEvt_SceneModeSet],
	"WDR",		[(SceneMode)appMenuEvt_SceneModeSet],
	"HDR",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Panorama",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Blink Detect",		[(SceneMode)appMenuEvt_SceneModeSet],
	"Voice Rec",		[(SceneMode)appMenuEvt_SceneModeSet],
"Card Error",
	"Card Error",
		"Format...",
[MARK]MENU_MARK_FORMAT_YES:
			"Yes",
[MARK]MENU_MARK_FORMAT_NO:
			"No",
		"Delete This File?",
[MARK]MENU_MARK_DELONE_YES:
			"Yes",
[MARK]MENU_MARK_DELONE_NO:
			"No",
		"Detecting Blinking...",
[MARK]MENU_MARK_BLINK_SAVE:
			"Save",
[MARK]MENU_MARK_BLINK_CANCEL:
			"Cancel",
		"Crop this photo?",
[MARK]MENU_MARK_JPG_CROP_YES:
			"Yes",
[MARK]MENU_MARK_JPG_CROP_NO:
			"No",
		"Please select Filetype!",		[(fileType)],
[MARK]MENU_MARK_FILETYPE_EVENT:
			"EVENT",		[(fileType)appMenuEvt_FileTypeSet],
			"VIDEO",		[(fileType)appMenuEvt_FileTypeSet],
			"JPG",		[(fileType)appMenuEvt_FileTypeSet],
"RedEyeSave",
[MARK]MENU_MARK_REDEYE_WRITE:
	"OverWrite",
[MARK]MENU_MARK_REDEYE_SAVE:
	"Save as",
[MARK]MENU_MARK_REDEYE_CANCEL:
	"Cancel",
[MARK]MENU_MARK_CALIBRATION:
"Calibration",
	"CALIB INFO",
	"OB CLBT",
	"M_SHUTTER",
	"ISO CLBT(LV11)",
	"Diff ISO OB CLBT",
[MARK]MENU_MARK_WBCLBT:
	"WB CLBT",
		"Back",
		"Calib_Awb",
		"Creat_Ctt",
		"Creat_Lv10_Calibration",
		"Creat_Lv10_Standard",
	"FOCUS",
[MARK]MENU_MARK_FLASH:
	"FLASH",
		"Back",
		"Pre-Analyses",
		"H_POS Scan",
		"Duration Scan",
	"View DPC",
	"Capture DPC",
	"BATTERY",
[MARK]MENU_MARK_CAMCONFIG:
	"+CAM CONFIG",
		"FW Update",
		"Factory Default",
		"PV SaveRaw",
		"CAP SaveRaw",
		"RawBatch Enable",
		"Prefh Stamp",
		"AF Full Scan",
[MARK]MENU_MARK_TESTBENCH:
	"+TEST BENCH",
		"Test Robot",
		"+Sensor",
			"Back",
			"IRIS Diff LV12",
			"Mini Gain LV12",
			"PV LV 4-16",
			"CAP LV 4-16",
			"P2...",
		"CIPA",
		"LCD Test",
		"KEY Test",
		"AE Meter",
		"+FLASH",
			"Back",
			"Curve A0",
			"Curve A1",
			"Curve B0",
			"Curve B1",
			"P2",
		"+AF",
			"Noise Coring Value Test",
			"Noise Coring Theshold Test",
			"Noise Theshoid Test",
			"Back",
		"BATTERY_CURVE",
		"AE debug",
		"AWB debug",
	"USB ISP",
	"Stand_alone LSC",
	"PV OB Cal",
	"VIDEO REC LOG",
	"Digital Zoom",
	"Touch Panel",

[STRING]:
	"Enter",
	"Back",
	"Delete This File?",
	"Delete All File?",
	"Formatting...",
	"Has no size to risize!",
	"File Locked!",
	"Protect File?",
	"Unprotect File?",
	"Protect All?",
	"Unprotect All?",
	"No File",
	"No Card!",
	"Remove Card!",
	"Card Error",
	"Waiting...",
	"Card Locked!",
	"Pause",
	"REC",
	"File Error!",
	"Please plug out card",
	"Memory Full",
	"Memory not enough",
	"Waiting for printer",
	"No Jpeg",
	"Format Fail!",
	"Low Battery",
	"Not Support!",
	"Cancel",
	"Select up to 24",
	"Please select a picture",
	"Print Error",
	"Not Find Printer",
	"Crop this photo?",
	"PictBridge",
	"Yes",
	"No",
	"Set this photo?",
	"Review this file?",
	"Save this file?",
	"Delete",
	"All",
	"Select",
	"Copy to card",
	"Copy this file?",
	"Copy all files?",
	"Rotate",
	"Rotate this photo?",
	"Save",
	"Set",
	"Stop",
	"Delete voice memo?",
	"Ready to record",
	"Ready to Play",
	"Recording memo...",
	"Playing audio...",
	"Trim this photo?",
	"Copy error",
	"Capture not enough size",
	"Capture Done",
	"Busy...Please wait",
	"Not available for this file",
	"Image saved",
	"Choose This Photo?",
	"Print All Photo?",
	"Set Print Copies",
	"Paper error",
	"Load error",
	"Eject error",
	"Paper jam",
	"Ink empty",
	"Ink low",
	"Waste ink",
	"Fatal error",
	"Service call",
	"Printer busy",
	"Lever error",
	"Cover open",
	"Ink cover open",
	"No ink cartridge",
	"Info error",
	"USB error",
	"Connecting",
	"Printing...",
	"Cancelling",
	"No paper",
	"Play",
	"Display File",
	"Completed",
	"Not_Support_C2C",
	"Find start",
	"Find end",
	"and press OK",
	"Writing Video",
	"Writing File Fail",
	"Trim Video is too Short",
	"Factory Reset",
	"Menu",
	"VIDEO",
	"SLOW",
	"PHOTO",
	"LAPSE",
	"BURST",
	"TIMER",
	"WIFI",
	"INIT...",
	"CONN...",
	"READY",
	"DEL",
	"SETUP",
	"HDMI",
	"HDMI PB",
	"USB",
	"MSDC",
	"BURN",
	"CARD ISP",
	"RF SCANNING",
	"Display",
	"Play_Pause",

#endif /* _MENU_RES_H_ */
