app_tb_cipa.o: app_tb_cipa.c \
  ../../../../customization/HostFw/include/app_com_def.h \
  ../../../../../spca5310/inc/common.h \
  ../../../../../spca5310/inc/api/sp5k_os_api.h \
  ../../../../../spca5310/inc/common.h \
  ../../../../../spca5310/inc/os/_tx_api.h \
  ../../../../../spca5310/inc/os/_tx_port.h \
  ../../../../../spca5310/inc/common.h \
  ../../../../../spca5310/inc/api/sp5k_msg_def.h \
  ../../../../../spca5310/inc/api/sp5k_modesw_api.h \
  ../../../../../spca5310/inc/api/sp5k_global_api.h \
  ../../../../../spca5310/inc/middleware/global_def.h \
  ../../../../../spca5310/inc/middleware/sensor_def.h \
  ../../../../../spca5310/inc/common.h \
  ../../../../../spca5310/inc/middleware/cdsp_def.h \
  ../../../../../spca5310/inc/middleware/snap_def.h \
  ../../../../../spca5310/inc/api/sp5k_fs_api.h \
  ../../../../../spca5310/inc/middleware/fs_def.h \
  ../../../../../spca5310/inc/api/sp5k_dcf_api.h \
  ../../../../../spca5310/inc/middleware/proflog.h \
  ../../../../customization/HostFw/include/app_sys_def.h \
  ../../../../include/customization/solution_def.h \
  ../../../../customization/HostFw/include/app_key_def.h \
  ../../../../../spca5310/inc/api/sp5k_msg_def.h \
  ../../../../customization/HostFw/include/app_key_msg.h \
  ../../../../customization/HostFw/include/app_ui_msg.h \
  ../../../../customization/HostFw/include/app_dbg_api.h \
  ../../../../../spca5310/inc/api/sp5k_dbg_api.h \
  ../../../../customization/HostFw/include/app_state_ctrl.h \
  ../../../../customization/HostFw/include/app_util.h \
  ../../../../customization/HostFw/include/app_disk.h \
  ../../../../customization/HostFw/include/app_led.h \
  ../../../../customization/HostFw/include/app_user_setting.h \
  ../../../../customization/HostFw/include/app_res_def.h \
  ../../../../customization/HostFw/include/app_sound.h \
  ../../../../customization/HostFw/include/app_com_api.h \
  ../../../../../spca5310/inc/api/sp5k_gfx_api.h \
  ../../../../../spca5310/inc/middleware/gfx_def.h \
  ../../../../../spca5310/inc/middleware/fnt_def.h \
  ../../../../../spca5310/inc/middleware/str_def.h \
  ../../../../../spca5310/inc/api/sp5k_disp_api.h \
  ../../../../../spca5310/inc/middleware/disp_def.h \
  ../../../../customization/HostFw/include/app_timer.h \
  ../../../../customization/HostFw/include/app_com_debug.h \
  ../../../../customization/HostFw/include/app_osd.h \
  ../../../../customization/HostFw/include/app_pal.h \
  ../../../../customization/HostFw/include/app_icon.h \
  ../../../../../spca5310/inc/api/sp5k_global_api.h \
  ../../../../customization/HostFw/include/app_osd_api.h \
  ../../../../customization/HostFw/include/app_osd.h \
  ../../../../customization/HostFw/include/app_battery.h
