# /*******************************************************************************
# *
# *       Copyright (c) 2005-2010 by Sunplus mMedia Inc., Ltd.
# *
# *  This software is copyrighted by and is the property of Sunplus mMedia
# *  Inc., Ltd. All rights are reserved by Sunplus mMedia Inc., Ltd.
# *  This software may only be used in accordance with the corresponding
# *  license agreement. Any unauthorized use, duplication, distribution,
# *  or disclosure of this software is expressly forbidden.
# *
# *  This Copyright notice MUST not be removed or modified without prior
# *  written consent of Sunplus mMedia Inc., Ltd.
# *
# *  Sunplus mMedia Inc., Ltd. reserves the right to modify this software
# *  without notice.
# *
# *  Sunplus mMedia Inc., Ltd.
# *  19-1, Innovation First Road, Science-Based Industrial Park,
# *  Hsin-Chu, Taiwan, R.O.C.
# *
# *  File Description:
# *
# *  Author: Anmin Deng
# *
# *******************************************************************************/
#init empty simple flavor variables before any include
CFLAGS :=
ASFLAGS :=


HOST_ROOT := ../../..
include $(HOST_ROOT)/host.def
ifndef PLATFORM_PATH
PLATFORM_PATH := $(PLATFORM)
endif
PLATFORM_ROOT := $(HOST_ROOT)/../$(PLATFORM_PATH)
TOOL_PATH := $(HOST_ROOT)/../tool

# output
SRC_DIR   := .
DEST_DIR  := $(HOST_ROOT)/_$(PRJ_NAME)
OBJS_PATH := $(DEST_DIR)/_$(PLATFORM_PATH)

# Include the definition of tool chain
include $(PLATFORM_ROOT)/tool_chain.def

#---------------------------------------------------------------------------
# Variable definition:
#   1. Cross-compling tools
#   2. Linker script file
#   3. C complier options
#   4. Assembly compiler options
#   5. Linker options
#---------------------------------------------------------------------------
ifeq (cc,$(CC))
CC   := $(PREFIX)/gcc
AR   := $(PREFIX)/ar
ECHO := echo
endif

ifeq ($(dbg), 1)
GOAL := libdisp_custom_d.a
CFLAGS += -DDBG_FUNC_TRACE_EXT_EN=1
CFLAGS += -DDBG_ASSERT_EXT_EN=1
CFLAGS += -DDBG_PRINT_EXT_EN=1
else
ifeq ($(dbg), 2)
GOAL := libdisp_custom.a
CFLAGS += -DDBG_FUNC_TRACE_EXT_EN=1
CFLAGS += -DDBG_ASSERT_EXT_EN=1
CFLAGS += -DDBG_PRINT_EXT_EN=1
else
GOAL := libdisp_custom.a
CFLAGS += -DDBG_FUNC_TRACE_EXT_EN=0
CFLAGS += -DDBG_ASSERT_EXT_EN=0
CFLAGS += -DDBG_PRINT_EXT_EN=0
endif
endif


ifdef lvl
CFLAGS += -DDBG_PRINT_EXT_LVL=$(lvl)
endif

#CFLAGS += -Wall
CFLAGS += -O2
CFLAGS += -G 8
#CFLAGS += -ansi
CFLAGS += -msoft-float
CFLAGS += -I$(HOST_ROOT)/include
CFLAGS += -I$(PLATFORM_ROOT)/inc
CFLAGS += -EL

#---------------------------------------------------------------------------
# Intermediate objects
#---------------------------------------------------------------------------
OBJS :=
OBJS += disp_composite_tv_ntsc.o
OBJS += disp_composite_tv_pal.o

OBJS += disp_hdmi_tv_all.o

OBJS += disp_dummy_one.o

OBJS += disp_auo_a015an04_ups051.o
OBJS += disp_auo_a015an04_ups052.o

OBJS += disp_gp_gp024QS5_ups052.o
OBJS += disp_auo_a025bn01_ups051.o
OBJS += disp_auo_a025bn01_ups052_w320.o
OBJS += disp_auo_a025bn01_ccir656_w640.o
OBJS += disp_auo_a025bn01_yuv_w640.o

OBJS += disp_auo_a027dn01_ups052.o

OBJS += disp_tma_ts027caard02_ups052.o

OBJS += disp_tp_td025theb1_ups052.o
OBJS += disp_tp_td020theg1_ups052.o
OBJS += disp_tp_td025theea_ups052.o
#original rules are list below but have problem. use ugly workaround.
#OBJS += disp_ana_anx7150.o
#OBJS += ANX7150_Sys7150.o
#OBJS += ANX7150_System_Config.o
#OBJS += EP932_SysController.o
#OBJS += EP932_SystemConfig.o
OBJS += disp_ana_anx7150_dummy.o
OBJS += ANX7150_Sys7150_dummy.o
OBJS += ANX7150_System_Config_dummy.o
OBJS += Disp_EP_EP932_dummy.o
OBJS += EP932_SysController_dummy.o
OBJS += EP932_SystemConfig_dummy.o
OBJS += disp_auo_a024cn03_dummy.o
OBJS += disp_txd_txdt240tq_lcm_h.o
OBJS += disp_txd_txdt240tq_lcm_v.o
OBJS += disp_txd_txdt250c_ups052.o
OBJS += disp_wt_wdf9648w7flwa_ups052.o
OBJS += disp_wt_wdf9648w7flwa_ups051.o
OBJS += disp_djn_ili9225g_lcm.o
OBJS += disp_vsn_m01120_lcm.o

#---------------------------------------------------------------------------
# Referring to generic rules
#---------------------------------------------------------------------------
$(eval $(call GEN_GOAL_RULES))


#---------------------------------------------------------------------------
# Private rules
#---------------------------------------------------------------------------
$(BUILD_OBJS:.o=.d): %:
	#echo "private $<"
	@$(MKDIR) $(dir $@)
	@$(CC) $(CFLAGS) -MM -MT '$(@:.d=.o) $@' -o $@ $<

$(BUILD_OBJS): %:
	#echo "private $<"
	$(MSG_SPLIT_LINE)
	$(MSG_COMPILING)
	@$(CC) -c $(CFLAGS) -o $@ $<


define DISP_OPT_RULES
# disp opt upper case
 DISP_OPT_$(1)_$(2) := DISP_$$(shell /bin/sh -c \
		"echo '$(2)' | sed -e 's/\(.*\)/\U\1/'")

 $$(BUILD_DIR)/$(1)_$(2).d: $$(SRC_DIR)/$(1).c
 $$(BUILD_DIR)/$(1)_$(2).o: $$(SRC_DIR)/$(1).c $$(BUILD_DIR)/$(1)_$(2).d
 $$(BUILD_DIR)/$(1)_$(2).d: CFLAGS += -D$$(DISP_OPT_$(1)_$(2))=1
 $$(BUILD_DIR)/$(1)_$(2).o: CFLAGS += -D$$(DISP_OPT_$(1)_$(2))=1
endef


#
# disp_composite_tv.c
#
$(foreach opt,ntsc pal,$(eval \
	$(call DISP_OPT_RULES,disp_composite_tv,$(opt))))

#
# disp_hdmi_tv.c
#
$(foreach opt,all,$(eval \
	$(call DISP_OPT_RULES,disp_hdmi_tv,$(opt))))

#
# disp_dummy.c
#
$(foreach opt,one,$(eval \
	$(call DISP_OPT_RULES,disp_dummy,$(opt))))

#
# disp_auo_a015an04.c
#
$(foreach opt,ups051 ups052,$(eval \
	$(call DISP_OPT_RULES,disp_auo_a015an04,$(opt))))

#
# disp_gp_gp024QS5_ups052.c
#
$(foreach opt,ups051 ups052,$(eval \
	$(call DISP_OPT_RULES,disp_gp_gp024QS5_ups052,$(opt))))

#
# disp_auo_a025bn01.c
#
$(foreach opt,ups051 ups052_w320 ccir656_w640 yuv_w640,$(eval \
	$(call DISP_OPT_RULES,disp_auo_a025bn01,$(opt))))

#
# disp_auo_a027dn01.c
#
$(foreach opt,ups052,$(eval \
	$(call DISP_OPT_RULES,disp_auo_a027dn01,$(opt))))

#
# disp_auo_a030dl01.c
#
$(foreach opt,ups051 ups052,$(eval \
	$(call DISP_OPT_RULES,disp_auo_a030dl01,$(opt))))

#
# disp_tp_td025theb1.c
#
$(foreach opt,ups052,$(eval \
	$(call DISP_OPT_RULES,disp_tp_td025theb1,$(opt))))

#
# disp_gp_gp024QS5.c
#
$(foreach opt,ups052,$(eval \
	$(call DISP_OPT_RULES,disp_gp_gp024QS5,$(opt))))

#
# disp_tma_ts027caard02.c
#
$(foreach opt,ups052,$(eval \
	$(call DISP_OPT_RULES,disp_tma_ts027caard02,$(opt))))

#
# disp_tp_td020theg1.c
#
$(foreach opt,ups052,$(eval \
	$(call DISP_OPT_RULES,disp_tp_td020theg1,$(opt))))

# disp_tp_td025theea.c
#
$(foreach opt,ups052,$(eval \
	$(call DISP_OPT_RULES,disp_tp_td025theea,$(opt))))

#
# disp_txd_txdt240tq.c
#
$(foreach opt,lcm_h lcm_v,$(eval \
	$(call DISP_OPT_RULES,disp_txd_txdt240tq,$(opt))))

#
# disp_txd_txdt250c.c
#
$(foreach opt,ups052,$(eval \
	$(call DISP_OPT_RULES,disp_txd_txdt250c,$(opt))))

#
# disp_wt_wdf9648w7flwa.c
#
$(foreach opt,ups051 ups052,$(eval \
	$(call DISP_OPT_RULES,disp_wt_wdf9648w7flwa,$(opt))))

#
# disp_djn_ili9225g.c
#
$(foreach opt,lcm,$(eval \
	$(call DISP_OPT_RULES,disp_djn_ili9225g,$(opt))))

#
# disp_vsn_m01120.c
#
$(foreach opt,lcm,$(eval \
	$(call DISP_OPT_RULES,disp_vsn_m01120,$(opt))))

# Ugly workaround for disp_ana_anx7150.c, ANX7150_Sys7150.c,
# ANX7150_System_Config.c, EP932_SysController.c, EP932_SystemConfig.c
# Disp_EP_EP932.c, disp_auo_a024cn03.c
#
$(foreach opt,dummy,$(eval \
	$(call DISP_OPT_RULES,disp_ana_anx7150,$(opt))))

$(foreach opt,dummy,$(eval \
	$(call DISP_OPT_RULES,ANX7150_Sys7150,$(opt))))

$(foreach opt,dummy,$(eval \
	$(call DISP_OPT_RULES,ANX7150_System_Config,$(opt))))

$(foreach opt,dummy,$(eval \
	$(call DISP_OPT_RULES,Disp_EP_EP932,$(opt))))

$(foreach opt,dummy,$(eval \
	$(call DISP_OPT_RULES,EP932_SysController,$(opt))))

$(foreach opt,dummy,$(eval \
	$(call DISP_OPT_RULES,EP932_SystemConfig,$(opt))))

$(foreach opt,dummy,$(eval \
	$(call DISP_OPT_RULES,disp_auo_a024cn03,$(opt))))

